# Generated by Django 4.1.5 on 2023-03-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.AlterField(
            model_name='room',
            name='user_1',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
