# Generated by Django 4.2 on 2023-04-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='user_1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='room',
            name='user_2',
            field=models.CharField(max_length=500),
        ),
    ]
