# Generated by Django 4.2 on 2023-05-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_name',
        ),
        migrations.AddField(
            model_name='room',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='room',
            name='delete_user_1',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='delete_user_2',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='user_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='user_2',
            field=models.CharField(max_length=100),
        ),
    ]
