# Generated by Django 4.1.5 on 2023-03-13 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_room_id_alter_room_user_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='user_1',
            new_name='room_name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='user_2',
        ),
    ]
