# Generated by Django 4.2 on 2023-05-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_room_room_name_room_id_alter_message_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='delete_user_1',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='room',
            name='delete_user_2',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='room',
            name='user_1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='room',
            name='user_2',
            field=models.CharField(max_length=30),
        ),
    ]
