# Generated by Django 4.1.5 on 2023-03-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_user_1_room_room_name_remove_room_user_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user_1',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='user_2',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
