# Generated by Django 4.2 on 2023-04-21 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_delete_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='delete_number',
        ),
    ]
