# Generated by Django 4.2 on 2023-04-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_room_delete_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='delete_user_1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='room',
            name='delete_user_2',
            field=models.CharField(default='', max_length=500),
        ),
    ]
