# Generated by Django 4.1.5 on 2023-03-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_room_user_1_room_user_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='user_1',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='room',
            name='user_2',
            field=models.CharField(max_length=128),
        ),
    ]
