# Generated by Django 4.2 on 2023-04-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_room_delete_user_1_room_delete_user_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='delete_user_1',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='room',
            name='delete_user_2',
            field=models.CharField(default='0', max_length=500),
        ),
    ]
