# Generated by Django 4.1.5 on 2023-03-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=models.TextField(max_length=2500),
        ),
    ]
