# Generated by Django 4.2 on 2023-05-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_blog_options_usersettings_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='low_power_mode',
            field=models.BooleanField(default=False),
        ),
    ]
