# Generated by Django 4.2 on 2023-05-25 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_blog_options_usersettings_theme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name_plural': 'UserSettings'},
        ),
    ]
