# Generated by Django 4.1.5 on 2023-03-11 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_usersettings_id_alter_usersettings_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='subscriber',
            new_name='subscribe',
        ),
    ]
